version: '3.8'

services:
  textbook-web-php-laravel-web:
    container_name: 'textbook.web.php.laravel.web'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '1111:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - textbook-web-php-laravel-php
      - textbook-web-php-laravel-mysql
  textbook-web-php-laravel-php:
    container_name: 'textbook.web.php.laravel.php'
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    #command: php artisan serve --port 3000

  textbook-web-php-laravel-mysql:
    container_name: 'textbook.web.php.laravel.mysql'
    image: mysql:5.7
    env_file:
      - ./db/env/mysql.env
    volumes:
      - ./db/data:/var/lib/mysql

  textbook-web-php-laravel-myadmin:
    container_name: 'textbook.web.php.laravel.myadmin'
    depends_on:
      - textbook-web-php-laravel-mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: textbook-web-php-laravel-mysql
    restart: always
    ports:
      - "1112:80"

networks:
  default:
    external:
      name: rd-shared